lib/flowr_web/router.ex
defmodule FlowrWeb.Router do
  use FlowrWeb, :router
  import Phoenix.LiveView.Router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {FlowrWeb.LayoutView, :root}
    plug FlowrWeb.Plugs.SetCurrentCustomer
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :dashboard do
    plug FlowrWeb.Plugs.AuthenticateCustomer
    plug :put_layout, {FlowrWeb.LayoutView, :dashboard}
  end

  pipeline :developer do
    plug :put_layout, {FlowrWeb.LayoutView, :developer}
  end

  scope "/", FlowrWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/templates", TemplateController

    scope "/developer", as: :developer, alias: Developer do
      pipe_through :developer

      get "/", DeveloperController, :index

      resources "/connectors", ConnectorController
    end

    scope "/dashboard", as: :dashboard, alias: Dashboard do
      pipe_through [:dashboard]

      get "/", DashboardController, :index

      resources "/subscriptions", SubscriptionController do
        resources "/logs", Subscription.LogController, only: [:index]
      end

      resources "/pollings", PollingController do
        resources "/items", Polling.ItemController, only: [:index]
      end

      resources "/triggers", TriggerController

      get "/tasks", FlowTaskController, :index_all, as: :task
      resources "/tasks", FlowTaskController, as: :task, only: [:show]

      resources "/flows", FlowController do
        resources "/tasks", FlowTaskController, as: :task, only: [:index]
      end

      resources "/connectors", ConnectorController, only: [:index]

      resources "/connector_accounts", AccountController, as: :connector_account

      get "/connector_accounts/:id/auth", AccountController, :auth, as: :connector_account
    end
  end

  scope "/auth", FlowrWeb do
    pipe_through(:browser)

    get "/new", AuthController, :new
    get "/callback", AuthController, :callback
    delete "/sign-out", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  scope path: "/api", as: :api, alias: FlowrWeb.API do
    pipe_through :api

    post("/subscriptions/:id/", SubscriptionController, :create)
    post("/webhook/:id/", WebhookController, :create)
    get("/connectors/callback", ConnectorAccountController, :callback)
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      live_dashboard "/dashboard",
        ecto_repos: [Flowr.Repo],
        additional_pages: [
          broadway: {BroadwayDashboard, pipelines: [Flowr.Automation.Workflow]}
        ]
    end
  end
end

lib/flowr_web/views/layout_view.ex
defmodule FlowrWeb.LayoutView do
  use FlowrWeb, :view

  @spec current_customer(Plug.Conn.t()) :: Flowr.Accounts.Customer.t()
  def current_customer(conn) do
    conn.assigns[:current_customer]
  end
end

lib/flowr_web/templates/layout/_nav.html.eex
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f0f8fc;">
  <%= link to: Routes.page_path(@conn, :index), class: "navbar-brand" do %>
    <img src='<%= Routes.static_path(@conn, "/images/logo.svg") %>' width="40" height="40" alt="">
    Flowr
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <%= if current_customer(@conn) do %>
        <li class="nav-item">
          <%= active_link @conn, "Dashboard", to: Routes.dashboard_dashboard_path(@conn, :index), class: "nav-link"%>
        </li>
      <% end %>
      <li class="nav-item">
        <%= active_link @conn, "Templates", to: Routes.template_path(@conn, :index), class: "nav-link"%>
      </li>
    </ul>
    <ul class="navbar-nav">
      <%= if current_customer(@conn) do %>
        <li class="nav-item">
          <%= active_link @conn, "Developer Console", to: Routes.developer_developer_path(@conn, :index), class: "nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user"></i>
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">
              Customer: <%= current_customer(@conn).owner_id %>
            </a>
            <a class="dropdown-item" href="#">Settings <small>(coming soon)</small></a>
            <%= link "Sign Out", to: Routes.auth_path(@conn, :delete), method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link "Sign In", to: Routes.auth_path(@conn, :new), class: "nav-link", class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

lib/flowr_web/templates/layout/_nav.html.heex
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #f0f8fc;">
  <%= link to: Routes.page_path(@conn, :index), class: "navbar-brand" do %>
    <img src={Routes.static_path(@conn, "/images/logo.svg")} width="40" height="40" alt="">
    Flowr
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <%= if current_customer(@conn) do %>
        <li class="nav-item">
          <%= active_link @conn, "Dashboard", to: Routes.dashboard_dashboard_path(@conn, :index), class: "nav-link"%>
        </li>
      <% end %>
      <li class="nav-item">
        <%= active_link @conn, "Templates", to: Routes.template_path(@conn, :index), class: "nav-link"%>
      </li>
    </ul>
    <ul class="navbar-nav">
      <%= if current_customer(@conn) do %>
        <li class="nav-item">
          <%= active_link @conn, "Developer Console", to: Routes.developer_developer_path(@conn, :index), class: "nav-link"%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            Customer: <%= current_customer(@conn).owner_id %>
          </a>
        </li>
        <li class="nav-item">
          <%= link "Sign Out", to: Routes.auth_path(@conn, :delete), method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link "Sign In", to: Routes.auth_path(@conn, :new), class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

lib/flowr_web/templates/layout/app.html.heex
<div class="container">
  <%= render "_nav.html", assigns %>

  <%= if get_flash(@conn, :info) do %>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <% end %>

  <%= if get_flash(@conn, :error) do %>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <% end %>

  <div class="mt-3">
    <div class="row">
      <div class="col-12">
        <%= @inner_content %>
      </div>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/dashboard.html.eex
<div class="container">
  <%= render "_nav.html", assigns %>

  <div class="mt-3">
    <div class="row">
      <div class="col-3">
        <ul class="nav nav-pills flex-column">
          <%= if current_customer(@conn) do %>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_trigger_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-bolt"></i>
                Triggers
              <% end %>
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_flow_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-project-diagram"></i>
                Flows
              <% end %>
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_task_path(@conn, :index_all), class: "nav-link" do %>
                <i class="fa fa-history"></i>
                Tasks
              <% end %>
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_connector_account_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-user-circle"></i>
                Accounts
              <% end %>
            </li>
            <li class="nav-item">
            <hr />
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_connector_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-plug"></i>
                Connectors
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-9">
        <%= @inner_content %>
      </div>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/dashboard.html.heex
<div class="container">
  <%= render "_nav.html", assigns %>

  <div class="mt-3">
    <div class="row">
      <div class="col-3">
        <ul class="nav nav-pills flex-column">
          <%= if current_customer(@conn) do %>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_trigger_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-bolt"></i>
                Triggers
              <% end %>
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_flow_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-project-diagram"></i>
                Flows
              <% end %>
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_task_path(@conn, :index_all), class: "nav-link" do %>
                <i class="fa fa-history"></i>
                Tasks
              <% end %>
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_connector_account_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-user-circle"></i>
                Accounts
              <% end %>
            </li>
            <li class="nav-item">
            <hr />
            </li>
            <li class="nav-item">
              <%= active_link @conn, to: Routes.dashboard_connector_path(@conn, :index), class: "nav-link" do %>
                <i class="fa fa-plug"></i>
                Connectors
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-9">
        <%= @inner_content %>
      </div>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/developer.html.eex
<div class="container">
  <%= render "_nav.html", assigns %>

  <div class="mt-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= active_link @conn, "Manage Connectors", to: Routes.developer_connector_path(@conn, :index), class: "nav-link"%>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Settings <small>(coming soon)</small></a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Analytics <small>(coming soon)</small></a>
      </li>
    </ul>
    <div class="mt-3">
      <%= @inner_content %>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/developer.html.heex
<div class="container">
  <%= render "_nav.html", assigns %>

  <div class="mt-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <%= active_link @conn, "Manage Connectors", to: Routes.developer_connector_path(@conn, :index), class: "nav-link"%>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Settings <small>(coming soon)</small></a>
      </li>
      <li class="nav-item">
        <a href="#" class="nav-link">Analytics <small>(coming soon)</small></a>
      </li>
    </ul>
    <div class="mt-3">
      <%= @inner_content %>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/live.html.heex
<div class="container">
  <div class="mt-3">
    <div class="row">
      <div class="col-12">
        <%= @inner_content %>
      </div>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/live.html.leex
<div class="container">
  <div class="mt-3">
    <div class="row">
      <div class="col-12">
        <%= @inner_content %>
      </div>
    </div>
  </div>
</div>

lib/flowr_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>

    <%= csrf_meta_tag() %>

    <.live_title>
      <%= assigns[:page_title] || "Flowr" %>
    </.live_title>

    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />

    <script defer src="https://use.fontawesome.com/releases/v5.8.2/js/all.js" integrity="sha384-DJ25uNYET2XCl5ZF++U8eNxPWqcKohUUBUpKGlNLMchM7q4Wjg2CUpjHLaL8yYPH" crossorigin="anonymous"></script>
    <script defer type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="apple-touch-icon" sizes="180x180" href={Routes.static_path(@conn, "/apple-touch-icon.png")}>
    <link rel="icon" type="image/png" sizes="32x32" href={Routes.static_path(@conn, "/favicon-32x32.png")}>
    <link rel="icon" type="image/png" sizes="16x16" href={Routes.static_path(@conn, "/favicon-16x16.png")}>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>